"""create games 2

Revision ID: 35b42beb3206
Revises: 65f18c6cfcaa
Create Date: 2024-10-17 03:47:08.234459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b42beb3206'
down_revision = '65f18c6cfcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
